extends: airbnb-base
env:
  browser: true
  commonjs: true
  es6: true
  jquery: true
globals:
  Modularity: true
  tinymce: true
rules:
  indent: ["error", 4]
  no-param-reassign: [2, { "props": false }]
