image: ubuntu2004
stack: node 14
build: off

for:
  - deploy: off
    branches:
      except:
        - master
        - develop
        - /\d+\.\d+\.\d+/

cache:
  - node_modules -> package.json, package-lock.json

install:
  - sudo apt-get update
  - sudo apt-get -fy install composer httpie php-codesniffer slugify

before_build:
  - 'PROJECT="$(composer config name)"'
  - 'TAG="$(git describe --match="[0-9]*" --abbrev=0 --tags)"'
  - 'BUILD="$TAG.$APPVEYOR_BUILD_NUMBER"'
  - 'SUFFIX="$(test -z $APPVEYOR_REPO_TAG_NAME && echo "-dev" || true)"'
  - 'VERSION="${APPVEYOR_REPO_TAG_NAME:-$BUILD}${SUFFIX}"'
  - 'ARTIFACT="$(slugify $PROJECT $VERSION).zip"'

build_script:
  - composer config version "$VERSION"
  - bash build.sh

after_build:
  - zip -r "$ARTIFACT" . -x ".git*" -x "node_modules/*" -x "vendor/*/*"

deploy_script: >
  http --form POST
  "$WPR_HOST/publish.php"
  "Authorization: Key $WPR_KEY"
  "files[]@$ARTIFACT"
  --check-status
  --timeout 600

artifacts:
  - path: '*.zip'
